/**
 * Shiyarah Weddings — Site Data
 * Chennai-based luxury wedding photography studio
 */

import type {
  NavItem,
  Service,
  PortfolioItem,
  Testimonial,
  PricingPackage,
  TeamMember,
  Award,
  BlogPost,
  Stat,
  VideoItem,
  ServicePricing,
  WeddingAlbum,
} from "./types";

// ─── Studio Contact Info ──────────────────────────────────────────────────────

export const studioInfo = {
  name: "Shiyarah Weddings",
  tagline: "Crafting Timeless Love Stories",
  phone: "+91 72007 35915",
  phoneRaw: "+917200735915",
  email: "hello@shiyarahweddings.com",
  address: "No. 14, Anna Nagar East, Chennai – 600 102, Tamil Nadu",
  whatsapp: "https://wa.me/917200735915?text=Hi%2C%20I%27d%20like%20to%20book%20a%20session%20with%20Shiyarah%20Weddings",
  instagram: "https://instagram.com/shiyarahweddings",
  facebook: "https://facebook.com/shiyarahweddings",
  youtube: "https://youtube.com/@shiyarahweddings",
  mapsUrl: "https://maps.google.com/?q=Anna+Nagar+East+Chennai",
  city: "Chennai, Tamil Nadu",
};

// ─── Navigation ───────────────────────────────────────────────────────────────

export const navItems: NavItem[] = [
  { label: "Home", href: "/" },
  {
    label: "Portfolio",
    href: "/portfolio",
    children: [
      { label: "All Work", href: "/portfolio" },
      { label: "Wedding Photography", href: "/portfolio/wedding" },
      { label: "Reception", href: "/portfolio/reception" },
      { label: "Pre-Wedding", href: "/portfolio/pre-wedding" },
      { label: "Maternity", href: "/portfolio/maternity" },
      { label: "Baby Shoots", href: "/portfolio/baby" },
    ],
  },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "Wedding Photography", href: "/services/wedding" },
      { label: "Reception Photography", href: "/services/reception" },
      { label: "Pre-Wedding Shoot", href: "/services/pre-wedding" },
      { label: "Maternity Photography", href: "/services/maternity" },
      { label: "Baby Photography", href: "/services/baby" },
      { label: "Events Coverage", href: "/services/events" },
    ],
  },
  { label: "About", href: "/about" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

// ─── Stats ────────────────────────────────────────────────────────────────────

export const heroStats: Stat[] = [
  { value: "800+", label: "Happy Couples", icon: "Heart" },
  { value: "400+", label: "Weddings Covered", icon: "Camera" },
  { value: "6+", label: "Years Experience", icon: "Award" },
  { value: "4.9★", label: "Google Rating", icon: "Star" },
];

// ─── Services ─────────────────────────────────────────────────────────────────

export const services: Service[] = [
  {
    id: "wedding",
    title: "Wedding Photography",
    description:
      "We capture the sacred vows, the stolen glances, and every emotion of your Tamil wedding with poetic cinematic artistry.",
    icon: "Heart",
    image: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85",
    href: "/services/wedding",
    features: [
      "Full day coverage",
      "2 lead photographers",
      "Candid + traditional shots",
      "Drone aerial coverage",
      "Same-day highlight reel",
      "Premium heirloom album",
    ],
  },
  {
    id: "reception",
    title: "Reception Photography",
    description:
      "From the grand entrance to the last dance — your reception night captured with breathtaking candid and staged elegance.",
    icon: "Sparkles",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=85",
    href: "/services/reception",
    features: [
      "Evening coverage",
      "Stage & décor shots",
      "Candid guest moments",
      "Group photographs",
      "Quick digital delivery",
      "Online gallery access",
    ],
  },
  {
    id: "pre-wedding",
    title: "Pre-Wedding Shoot",
    description:
      "A romantic storytelling session before your big day. Choose Chennai's iconic locations or a scenic outstation destination.",
    icon: "Camera",
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=85",
    href: "/services/pre-wedding",
    features: [
      "Location scouting",
      "Wardrobe consultation",
      "2–3 outfit changes",
      "Cinematic highlight video",
      "Edited full gallery",
      "Print-ready files",
    ],
  },
  {
    id: "maternity",
    title: "Maternity Photography",
    description:
      "The glow of motherhood, beautifully immortalised. Intimate studio and outdoor maternity sessions crafted just for you.",
    icon: "Baby",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=85",
    href: "/services/maternity",
    features: [
      "Studio & outdoor options",
      "Professional styling guidance",
      "Partner & family inclusion",
      "Belly art (optional)",
      "High-res edited gallery",
      "Print collection",
    ],
  },
  {
    id: "baby",
    title: "Baby Photography",
    description:
      "Tiny toes, sleepy smiles, first yawns — delicate newborn portraits crafted with the utmost safety and tenderness.",
    icon: "Star",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=85",
    href: "/services/baby",
    features: [
      "Certified newborn posing",
      "Safety-first approach",
      "Family portrait inclusion",
      "Themed prop setups",
      "Milestone shoot bundles",
      "Keepsake photo book",
    ],
  },
  {
    id: "events",
    title: "Events & Videography",
    description:
      "Engagements, naming ceremonies, birthday galas, corporate events — cinematic coverage for every milestone.",
    icon: "Video",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=85",
    href: "/services/events",
    features: [
      "Full event coverage",
      "4K cinematic video",
      "Drone aerial shots",
      "Multi-camera setup",
      "Live event reels",
      "Fast post-production",
    ],
  },
];

// ─── Why Choose Us ─────────────────────────────────────────────────────────────

export const whyChooseUs = [
  {
    icon: "Camera",
    title: "Artisan Photography",
    description: "Sony & Canon pro gear, medium-format film look — every shot is a frame-worthy artwork.",
  },
  {
    icon: "Film",
    title: "Cinematic Films",
    description: "Hollywood-grade colour grading and storytelling transforms your day into an eternal film.",
  },
  {
    icon: "Palette",
    title: "Signature Editing",
    description: "Our warm, filmic edit style is unique to Shiyarah — you'll recognise it instantly.",
  },
  {
    icon: "Zap",
    title: "7-Day Delivery",
    description: "Sneak peeks within 48 hours, full gallery in 7 days — we never keep you waiting.",
  },
  {
    icon: "BookOpen",
    title: "Heirloom Albums",
    description: "Flush-mount lay-flat albums printed on Italian archival paper — made to last generations.",
  },
  {
    icon: "Navigation",
    title: "Drone Coverage",
    description: "Licensed drone operators deliver sweeping aerial footage that adds cinematic scale.",
  },
];

// ─── Portfolio Items ──────────────────────────────────────────────────────────
// Real-looking Tamil wedding photography via Unsplash

export const portfolioItems: PortfolioItem[] = [
  {
    id: "p1",
    title: "Sacred Saptapadi",
    category: "weddings",
    image: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=700&q=85",
    width: 700, height: 933, featured: true,
  },
  {
    id: "p2",
    title: "Candlelit Reception",
    category: "reception",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=700&q=85",
    width: 700, height: 467, featured: true,
  },
  {
    id: "p3",
    title: "Sunrise Pre-Wedding",
    category: "pre-wedding",
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=700&q=85",
    width: 700, height: 880, featured: true,
  },
  {
    id: "p4",
    title: "Golden Maternity",
    category: "maternity",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&q=85",
    width: 700, height: 900, featured: true,
  },
  {
    id: "p5",
    title: "Newborn Serenity",
    category: "baby",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=700&q=85",
    width: 700, height: 700, featured: true,
  },
  {
    id: "p6",
    title: "Grand Mandap",
    category: "events",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=700&q=85",
    width: 700, height: 525, featured: true,
  },
  {
    id: "p7",
    title: "Thirumanam Moments",
    category: "weddings",
    image: "https://images.unsplash.com/photo-1583939411023-14783179e581?w=700&q=85",
    width: 700, height: 1050,
  },
  {
    id: "p8",
    title: "Marina Beach Romance",
    category: "pre-wedding",
    image: "https://images.unsplash.com/photo-1529634806980-85c3dd6d34ac?w=700&q=85",
    width: 700, height: 840,
  },
  {
    id: "p9",
    title: "First Breath",
    category: "baby",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=700&q=85",
    width: 700, height: 700,
  },
  {
    id: "p10",
    title: "Jasmine & Light",
    category: "reception",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=700&q=85",
    width: 700, height: 525,
  },
  {
    id: "p11",
    title: "Bloom & Grace",
    category: "maternity",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=700&q=85",
    width: 700, height: 875,
  },
  {
    id: "p12",
    title: "Engagement Gala",
    category: "events",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=700&q=85",
    width: 700, height: 467,
  },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Divya & Aravind",
    role: "Wedding Couple",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
    rating: 5,
    review:
      "Shiyarah Weddings transformed our Tamil Brahmin wedding into a visual poem. Every candid shot, every ritual — documented with such tenderness. Our album makes us cry tears of joy every single time.",
      event: "Wedding Photography · Chennai",
      date: "December 2024",
    },
    {
      id: "t2",
    name: "Keerthana & Vishnu",
    role: "Wedding Couple",
    image: "https://images.unsplash.com/photo-1522169182878-9a01f346c3d1?w=200&q=80",
    rating: 5,
    review:
      "The pre-wedding shoot at Mahabalipuram was absolutely breathtaking. They scouted the golden-hour spots perfectly and made us feel so comfortable in front of the camera. World-class work.",
    event: "Pre-Wedding Shoot · Mahabalipuram",
    date: "November 2024",
  },
  {
    id: "t3",
    name: "Priya Ramesh",
    role: "New Mother",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    rating: 5,
    review:
      "My maternity session was pure magic. The team created such a warm, serene atmosphere. The photos look like they belong in a fine-art gallery. I'm forever grateful.",
    event: "Maternity Photography · Studio Session",
    date: "October 2024",
  },
  {
    id: "t4",
    name: "Ranjitha & Karthick",
    role: "Wedding Couple",
    image: "https://images.unsplash.com/photo-1520880867055-1e30d1cb001c?w=200&q=80",
    rating: 5,
    review:
      "From our reception to the post-production, Shiyarah Weddings was professional, creative, and incredibly attentive to detail. Our highlight film made our extended family in the UK weep.",
    event: "Reception Photography · The Leela Chennai",
    date: "January 2025",
  },
  {
    id: "t5",
    name: "Ananya Suresh",
    role: "New Mother",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
    rating: 5,
    review:
      "Baby Rohan's newborn shoot was perfect in every way. Safety-first, super patient team who worked around our little one's schedule. The photos are heirlooms.",
    event: "Newborn Photography · Studio",
    date: "February 2025",
  },
  {
    id: "t6",
    name: "Meenakshi & Senthil",
    role: "Wedding Couple",
    image: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=200&q=80",
    rating: 5,
    review:
      "We are so happy we chose Shiyarah Weddings. The team captured every detail of our Murugan temple wedding beautifully. The cinematic video is our most treasured possession.",
    event: "Temple Wedding · Tiruchendur",
    date: "March 2025",
  },
];

// ─── Pricing Packages ─────────────────────────────────────────────────────────

export const pricingPackages: PricingPackage[] = [
  {
    id: "silver",
    name: "Silver",
    tier: "silver",
    price: 30000,
    currency: "₹",
    duration: "6 Hours",
    description: "Perfect for intimate ceremonies & small celebrations",
    features: [
      "6 Hours Coverage",
      "1 Lead Photographer",
      "350+ Edited Photos",
      "Online Gallery",
      "Digital Files (High-Res)",
      "Basic Retouching",
    ],
    cta: "Book Silver",
  },
  {
    id: "gold",
    name: "Gold",
    tier: "gold",
    price: 55000,
    currency: "₹",
    duration: "10 Hours",
    description: "Our most loved package for complete wedding coverage",
    features: [
      "10 Hours Coverage",
      "2 Lead Photographers",
      "700+ Edited Photos",
      "Cinematic Film (4 min)",
      "Drone Aerial Shots",
      "Premium Online Gallery",
      "Photo Book (24 pages)",
      "48-Hour Sneak Peek",
    ],
    popular: true,
    cta: "Book Gold",
  },
  {
    id: "platinum",
    name: "Platinum",
    tier: "platinum",
    price: 90000,
    currency: "₹",
    duration: "Full Day",
    description: "Comprehensive storytelling for your entire wedding journey",
    features: [
      "Full Day Coverage",
      "3 Photographers + 1 Videographer",
      "1200+ Edited Photos",
      "Cinematic Film (10 min)",
      "Drone Aerial Coverage",
      "Lay-Flat Heirloom Album",
      "Engagement Shoot Included",
      "Priority 7-Day Delivery",
      "Same-Day Teaser Reel",
    ],
    cta: "Book Platinum",
  },
  {
    id: "royal",
    name: "Royal",
    tier: "royal",
    price: 150000,
    currency: "₹",
    duration: "2–3 Days",
    description: "The ultimate luxury experience for grand celebrations",
    features: [
      "2–3 Day Full Coverage",
      "4+ Photographers & Videographers",
      "Unlimited Edited Photos",
      "Feature Cinematic Film (18 min)",
      "Multi-Location Drone",
      "Royal Lay-Flat Album (40 pages)",
      "Pre-Wedding Shoot Included",
      "WhatsApp Same-Day Teaser",
      "Dedicated Day-Of Coordinator",
      "Complimentary Fine-Art Prints",
      "VIP White-Glove Service",
    ],
    cta: "Book Royal",
  },
];

// ─── Team ─────────────────────────────────────────────────────────────────────

export const teamMembers: TeamMember[] = [
  {
    id: "tm1",
    name: "Shiyarah R",
    role: "Founder & Lead Photographer",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
    bio: "Shiyarah brings over 6 years of experience photographing Tamil weddings across Chennai, Coimbatore, and beyond. Her work has been featured in Vogue India and Brides Today.",
    social: { instagram: "https://instagram.com/shiyarahweddings", facebook: "https://facebook.com/shiyarahweddings" },
  },
  {
    id: "tm2",
    name: "Kavitha S",
    role: "Senior Photographer",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    bio: "Kavitha specialises in maternity, newborn, and family portraits — her gentle approach creates the most natural, emotional images imaginable.",
    social: { instagram: "https://instagram.com/shiyarahweddings" },
  },
  {
    id: "tm3",
    name: "Arjun M",
    role: "Lead Cinematographer",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    bio: "Arjun's cinematic wedding films have received millions of views. Licensed drone pilot with a background in Tamil cinema production.",
    social: { instagram: "https://instagram.com/shiyarahweddings" },
  },
  {
    id: "tm4",
    name: "Deepa L",
    role: "Photo Editor & Retoucher",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    bio: "Deepa's signature warm-filmic edit style is what sets Shiyarah apart visually. Her mastery of colour science brings a consistent, painterly tone to every gallery.",
    social: { instagram: "https://instagram.com/shiyarahweddings" },
  },
];

// ─── Awards ───────────────────────────────────────────────────────────────────

export const awards: Award[] = [
  {
    id: "a1",
    year: "2025",
    title: "Best Wedding Photographer — South India",
    organization: "South India Bridal Awards",
    description: "Recognised for outstanding artistic excellence and consistent client satisfaction.",
  },
  {
    id: "a2",
    year: "2024",
    title: "Top Luxury Studio — Tamil Nadu",
    organization: "WeddingWire India",
    description: "Voted #1 luxury photography studio in Tamil Nadu by couples.",
  },
  {
    id: "a3",
    year: "2024",
    title: "Best Cinematic Wedding Film",
    organization: "Indian Wedding Film Awards",
    description: "Gold award for the film 'Divya & Aravind — A Love Written in Jasmine'.",
  },
  {
    id: "a4",
    year: "2023",
    title: "Best Pre-Wedding Photography",
    organization: "Brides Today India",
    description: "Featured and awarded for the Mahabalipuram heritage shoot series.",
  },
  {
    id: "a5",
    year: "2022",
    title: "Rising Studio of the Year",
    organization: "Photography Guild India",
    description: "Named the fastest-growing luxury wedding studio in South India.",
  },
];

// ─── Blog Posts ───────────────────────────────────────────────────────────────

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "how-to-prepare-for-your-tamil-wedding-photoshoot",
    title: "How to Prepare for Your Tamil Wedding Photoshoot",
    excerpt:
      "A practical guide for couples — from choosing your kanjeevaram saree colours to building a comfortable timeline with your photographer.",
    content: "",
    image: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80",
    author: "Shiyarah R",
    authorImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
    date: "May 18, 2025",
    readTime: "8 min read",
    category: "Tips & Guides",
    tags: ["wedding", "photography", "tips", "tamil-wedding"],
  },
  {
    id: "b2",
    slug: "best-pre-wedding-shoot-locations-in-chennai",
    title: "The 8 Best Pre-Wedding Shoot Locations Near Chennai",
    excerpt:
      "From the sculpted corridors of Mahabalipuram to the golden dunes of Rameswaram — our curated location guide for romantic shoots.",
    content: "",
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
    author: "Kavitha S",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    date: "April 30, 2025",
    readTime: "6 min read",
    category: "Location Guides",
    tags: ["pre-wedding", "locations", "chennai", "outdoor"],
  },
  {
    id: "b3",
    slug: "maternity-photography-guide-chennai",
    title: "Maternity Photography: A Complete Guide for Chennai Moms",
    excerpt:
      "When to book, what to wear, which trimester is ideal, and how to feel radiant in front of the camera — everything covered.",
    content: "",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
    author: "Kavitha S",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    date: "April 12, 2025",
    readTime: "7 min read",
    category: "Photography Tips",
    tags: ["maternity", "pregnancy", "photography", "chennai"],
  },
  {
    id: "b4",
    slug: "behind-the-scenes-cinematic-wedding-films",
    title: "Behind the Lens: Creating Cinematic Tamil Wedding Films",
    excerpt:
      "An inside look at our filmmaking process — from pre-production planning to the final colour grade that makes every film look like a feature.",
    content: "",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
    author: "Arjun M",
    authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    date: "March 22, 2025",
    readTime: "10 min read",
    category: "Cinematography",
    tags: ["film", "cinematography", "wedding-video", "process"],
  },
  {
    id: "b5",
    slug: "newborn-photography-safety-guide",
    title: "Newborn Photography Safety: Our Promise to You",
    excerpt:
      "Safety is non-negotiable. Learn about our certified posing techniques, temperature management, and parent-reassurance protocols.",
    content: "",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
    author: "Shiyarah R",
    authorImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
    date: "March 5, 2025",
    readTime: "5 min read",
    category: "Baby Photography",
    tags: ["newborn", "baby", "safety", "photography"],
  },
  {
    id: "b6",
    slug: "choosing-the-right-wedding-package",
    title: "How to Choose the Right Photography Package for Your Wedding",
    excerpt:
      "Breaking down what each package truly covers and how to match your vision and guest count to the right investment tier.",
    content: "",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
    author: "Shiyarah R",
    authorImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
    date: "February 18, 2025",
    readTime: "9 min read",
    category: "Wedding Planning",
    tags: ["packages", "pricing", "wedding", "planning"],
  },
];

// ─── Videos ───────────────────────────────────────────────────────────────────

export const featuredVideos: VideoItem[] = [
  {
    id: "v1",
    title: "Divya & Aravind — A Love Written in Jasmine",
    description: "A two-day Tamil Brahmin wedding film, shot across Chennai and Chidambaram.",
    thumbnail: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80",
    videoUrl: "https://www.youtube.com/embed/6FBFxKFBCns",
    duration: "5:14",
    category: "Wedding Film",
  },
  {
    id: "v2",
    title: "Keerthana & Vishnu — Mahabalipuram Pre-Wedding",
    description: "A golden-hour pre-wedding film at the Shore Temple and Five Rathas.",
    thumbnail: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    duration: "3:28",
    category: "Pre-Wedding Film",
  },
  {
    id: "v3",
    title: "Grand Reception — The Leela Palace Chennai",
    description: "600 guests, a 30-piece orchestra, and one unforgettable night.",
    thumbnail: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    videoUrl: "https://www.youtube.com/embed/ZbZSe6N_BXs",
    duration: "3:02",
    category: "Reception Film",
  },
];


// ─── Wedding Albums (Pixieset) ────────────────────────────────────────────────

export const weddingAlbums: WeddingAlbum[] = [
  {
    id: "wa1",
    slug: "sarumathi-yeshwanth",
    couple: "Sarumathi & Yeshwanth",
    venue: "Sri Kapaleeshwarar Temple · Chennai",
    date: "February 2024",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=85",
    category: "Wedding",
    pixiesetUrl: "weddingblog",   // gallery ID on shiyarahweddings.pixieset.com
  },
  {
    id: "wa2",
    slug: "keerthana-vishnu",
    couple: "Keerthana & Vishnu",
    venue: "The Leela Palace · Chennai",
    date: "December 2023",
    coverImage: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85",
    category: "Wedding",
    pixiesetUrl: null,
  },
  {
    id: "wa3",
    slug: "meera-vikram",
    couple: "Meera & Vikram",
    venue: "Taj Coromandel · Chennai",
    date: "November 2023",
    coverImage: "https://images.unsplash.com/photo-1529634806980-85c3dd6d34ac?w=800&q=85",
    category: "Pre-Wedding",
    pixiesetUrl: null,
  },
  {
    id: "wa4",
    slug: "ananya-dev",
    couple: "Ananya & Dev",
    venue: "ITC Grand Chola · Chennai",
    date: "October 2023",
    coverImage: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=800&q=85",
    category: "Reception",
    pixiesetUrl: null,
  },
  {
    id: "wa5",
    slug: "priya-arjun",
    couple: "Priya & Arjun",
    venue: "Mahabalipuram Shore Temple",
    date: "September 2023",
    coverImage: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=85",
    category: "Wedding",
    pixiesetUrl: null,
  },
  {
    id: "wa6",
    slug: "riya-karan",
    couple: "Riya & Karan",
    venue: "Radisson Blu · Chennai",
    date: "August 2023",
    coverImage: "https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=800&q=85",
    category: "Wedding",
    pixiesetUrl: null,
  },
];


// ── Service-Based Pricing (Real Shiyarah Wedding Packages) ───────────────────

export const servicePricing: ServicePricing[] = [

  // ── WEDDING ────────────────────────────────────────────────────────────────
  {
    serviceId: "wedding",
    serviceLabel: "Wedding",
    icon: "💍",
    description: "Sacred vows, stolen glances, and every ritual — covered by a full team of candid and traditional artists.",
    packages: [
      {
        id: "wedding-silver",
        name: "Silver",
        price: 45000,
        currency: "₹",
        duration: "Reception + Wedding",
        description: "Our foundational package covering both reception and wedding with candid & traditional teams.",
        features: [
          "Reception Coverage",
          "Wedding Day Coverage",
          "1 Candid Photographer",
          "1 Candid Videographer",
          "1 Traditional Photographer",
          "1 Traditional Videographer",
          "Candid Video Highlights — 5 min",
          "Candid Teaser — 1 min",
          "30 Retouch Creative Photos",
          "2 Candid Reels",
          "Full HD Traditional Video",
          "Online Gallery Delivery",
        ],
        cta: "Book Silver",
      },
      {
        id: "wedding-gold",
        name: "Gold",
        price: 75000,
        currency: "₹",
        duration: "Reception + Wedding",
        description: "Everything in Silver plus premium album and pre/post wedding shoot.",
        popular: true,
        features: [
          "Reception Coverage",
          "Wedding Day Coverage",
          "1 Candid Photographer",
          "1 Candid Videographer",
          "1 Traditional Photographer",
          "1 Traditional Videographer",
          "Candid Video Highlights — 5 min",
          "Candid Teaser — 1 min",
          "30 Retouch Creative Photos",
          "2 Candid Reels",
          "Canvera Premium Album ×2",
          "12×30\" Big Album (250 pics each)",
          "Album Box & Combos",
          "Full HD Traditional Video",
          "Pre or Post Wedding Shoot (Photos only)",
          "25 Edited Pictures",
          "Photo Frame ×2",
          "Couple Calendar ×2",
        ],
        cta: "Book Gold",
      },
      {
        id: "wedding-platinum",
        name: "Platinum",
        price: 100000,
        currency: "₹",
        duration: "Multi-Day Grand",
        description: "Our flagship package — cinematic films, drone, and full luxury deliverables.",
        features: [
          "All Events Coverage",
          "2 Candid Photographers",
          "2 Candid Videographers",
          "1 Traditional Photographer",
          "1 Traditional Videographer",
          "Licensed Drone Aerial Coverage",
          "Cinematic Highlight Film — 10 min",
          "Candid Teaser — 1 min",
          "50+ Retouch Creative Photos",
          "4 Candid Reels",
          "Canvera Premium Album ×2",
          "12×30\" Big Album (250 pics each)",
          "Same-Day Teaser Reel",
          "Full HD Traditional Video",
          "Pre or Post Wedding Shoot",
          "Photo Frame ×2",
          "Couple Calendar ×2",
          "Priority 7-Day Delivery",
        ],
        cta: "Book Platinum",
      },
    ],
  },

  // ── RECEPTION ──────────────────────────────────────────────────────────────
  {
    serviceId: "reception",
    serviceLabel: "Reception",
    icon: "🥂",
    description: "Grand entrances, heartfelt speeches, and every joyful moment of your reception night.",
    packages: [
      {
        id: "reception-basic",
        name: "Essential",
        price: 20000,
        currency: "₹",
        duration: "4–5 Hours",
        description: "Core reception coverage — stills and a short highlight reel.",
        features: [
          "4–5 Hours Coverage",
          "1 Candid Photographer",
          "1 Traditional Photographer",
          "200+ Edited Photos",
          "Stage & Décor Shots",
          "Candid Guest Moments",
          "Online Gallery Delivery",
        ],
        cta: "Book Essential",
      },
      {
        id: "reception-premium",
        name: "Grand",
        price: 38000,
        currency: "₹",
        duration: "Full Evening",
        description: "Complete reception with candid & traditional teams plus cinematic highlights.",
        popular: true,
        features: [
          "Full Evening Coverage",
          "1 Candid Photographer",
          "1 Candid Videographer",
          "1 Traditional Photographer",
          "Candid Highlight Reel — 3 min",
          "400+ Edited Photos",
          "Group & Family Photographs",
          "Quick 48-Hour Delivery",
          "Online Gallery",
        ],
        cta: "Book Grand",
      },
      {
        id: "reception-luxury",
        name: "Luxury",
        price: 60000,
        currency: "₹",
        duration: "Full Evening + Album",
        description: "Premium reception coverage with album, drone and same-day teaser.",
        features: [
          "Full Evening Coverage",
          "2 Candid Photographers",
          "1 Candid Videographer",
          "1 Traditional Photographer",
          "Cinematic Film — 5 min",
          "Drone Aerial Shots",
          "600+ Edited Photos",
          "Lay-Flat Album (20 pages)",
          "Same-Day Teaser Reel",
          "Priority Delivery",
        ],
        cta: "Book Luxury",
      },
    ],
  },

  // ── PRE-WEDDING ────────────────────────────────────────────────────────────
  {
    serviceId: "pre-wedding",
    serviceLabel: "Pre-Wedding",
    icon: "🌅",
    description: "Romantic storytelling sessions — Chennai, Mahabalipuram, Ooty or your dream destination.",
    packages: [
      {
        id: "prewedding-studio",
        name: "Studio",
        price: 12000,
        currency: "₹",
        duration: "2–3 Hours",
        description: "Elegant studio session with professional lighting.",
        features: [
          "2–3 Hours Studio Session",
          "1 Photographer",
          "100+ Edited Photos",
          "2 Outfit Changes",
          "Professional Lighting Setup",
          "High-Res Digital Files",
        ],
        cta: "Book Studio",
      },
      {
        id: "prewedding-outdoor",
        name: "Outdoor",
        price: 22000,
        currency: "₹",
        duration: "Half Day",
        description: "Scenic outdoor shoot — Marina Beach, ECR, Mahabalipuram.",
        popular: true,
        features: [
          "Half Day (4–5 Hours)",
          "1 Photographer + Assistant",
          "200+ Edited Photos",
          "2–3 Outfit Changes",
          "Location Scouting",
          "Cinematic Highlight Clip",
          "Print-Ready Files",
        ],
        cta: "Book Outdoor",
      },
      {
        id: "prewedding-destination",
        name: "Destination",
        price: 45000,
        currency: "₹",
        duration: "Full Day",
        description: "Full-day destination shoot — Ooty, Kodaikanal, or wherever you dream.",
        features: [
          "Full Day Coverage",
          "2 Photographers",
          "400+ Edited Photos",
          "Multiple Location Changes",
          "Wardrobe Consultation",
          "Cinematic Film — 3 min",
          "Drone Aerial Shots",
          "Heirloom Photo Book",
        ],
        cta: "Book Destination",
      },
    ],
  },

  // ── MATERNITY ──────────────────────────────────────────────────────────────
  {
    serviceId: "maternity",
    serviceLabel: "Maternity",
    icon: "🤱",
    description: "The glow of motherhood beautifully immortalised — studio and outdoor sessions.",
    packages: [
      {
        id: "maternity-mini",
        name: "Mini",
        price: 8000,
        currency: "₹",
        duration: "1 Hour",
        description: "Quick, beautiful maternity portraits in studio.",
        features: [
          "1 Hour Studio Session",
          "1 Outfit",
          "50+ Edited Photos",
          "Fine-Art Retouching",
          "Online Gallery",
        ],
        cta: "Book Mini",
      },
      {
        id: "maternity-blossom",
        name: "Blossom",
        price: 15000,
        currency: "₹",
        duration: "2 Hours",
        description: "Our most loved — studio or outdoor with partner included.",
        popular: true,
        features: [
          "2 Hours (Studio or Outdoor)",
          "2 Outfits",
          "100+ Edited Photos",
          "Partner & Family Inclusion",
          "Styling Consultation",
          "Fine-Art Retouching",
          "Online Gallery",
        ],
        cta: "Book Blossom",
      },
      {
        id: "maternity-bloom",
        name: "Bloom",
        price: 25000,
        currency: "₹",
        duration: "3–4 Hours",
        description: "Premium experience with belly art, full styling, and printed album.",
        features: [
          "3–4 Hours (Studio + Outdoor)",
          "3 Outfits",
          "200+ Edited Photos",
          "Belly Art (optional)",
          "Hair & Makeup Coordination",
          "Full Family Inclusion",
          "Printed Photo Book",
          "Priority Delivery",
        ],
        cta: "Book Bloom",
      },
    ],
  },

  // ── NEWBORN ────────────────────────────────────────────────────────────────
  {
    serviceId: "newborn",
    serviceLabel: "Newborn",
    icon: "👶",
    description: "Tiny toes, sleepy smiles — delicate newborn portraits with safety-first certified posing.",
    packages: [
      {
        id: "newborn-tiny",
        name: "Tiny Toes",
        price: 7000,
        currency: "₹",
        duration: "1–2 Hours",
        description: "Essential newborn portraits in a safe, warm environment.",
        features: [
          "1–2 Hours Session",
          "Baby Poses Only",
          "60+ Edited Photos",
          "2 Prop Setups",
          "Online Gallery",
        ],
        cta: "Book Tiny Toes",
      },
      {
        id: "newborn-first",
        name: "First Light",
        price: 14000,
        currency: "₹",
        duration: "2–3 Hours",
        description: "Full newborn session with family portraits included.",
        popular: true,
        features: [
          "2–3 Hours Session",
          "Baby + Family Portraits",
          "100+ Edited Photos",
          "4–5 Prop Setups",
          "Safety-Certified Posing",
          "Themed Backdrops",
          "Online Gallery",
        ],
        cta: "Book First Light",
      },
      {
        id: "newborn-dream",
        name: "Dream Feather",
        price: 24000,
        currency: "₹",
        duration: "3–4 Hours",
        description: "Luxury session with milestone bundle and keepsake album.",
        features: [
          "3–4 Hours Full Session",
          "Baby + Full Family",
          "200+ Edited Photos",
          "Premium Prop Collection",
          "Milestone Bundle (3, 6, 12 months)",
          "Keepsake Photo Book",
          "Fine-Art Print Set",
          "Priority Delivery",
        ],
        cta: "Book Dream Feather",
      },
    ],
  },

  // ── ENGAGEMENT ─────────────────────────────────────────────────────────────
  {
    serviceId: "engagement",
    serviceLabel: "Engagement",
    icon: "💒",
    description: "Capture the magic of your engagement — intimate, joyful, and full of emotion.",
    packages: [
      {
        id: "engagement-promise",
        name: "Promise",
        price: 10000,
        currency: "₹",
        duration: "2 Hours",
        description: "Beautiful engagement portraits to announce your happy news.",
        features: [
          "2 Hours Coverage",
          "1 Photographer",
          "100+ Edited Photos",
          "Indoor/Outdoor Locations",
          "Online Gallery",
        ],
        cta: "Book Promise",
      },
      {
        id: "engagement-forever",
        name: "Forever",
        price: 20000,
        currency: "₹",
        duration: "3–4 Hours",
        description: "Extended coverage with cinematic highlight clip.",
        popular: true,
        features: [
          "3–4 Hours Coverage",
          "2 Photographers",
          "200+ Edited Photos",
          "Cinematic Clip — 2 min",
          "Multiple Locations",
          "Outfit Assistance",
          "Online Gallery",
        ],
        cta: "Book Forever",
      },
      {
        id: "engagement-golden",
        name: "Golden Hour",
        price: 35000,
        currency: "₹",
        duration: "Full Day",
        description: "Premium all-day engagement with drone and full film.",
        features: [
          "Full Day Coverage",
          "2 Photographers + Videographer",
          "400+ Edited Photos",
          "Cinematic Film — 4 min",
          "Drone Aerial Shots",
          "Engagement Album (20 pages)",
          "Priority Delivery",
        ],
        cta: "Book Golden Hour",
      },
    ],
  },

  // ── CORPORATE ──────────────────────────────────────────────────────────────
  {
    serviceId: "corporate",
    serviceLabel: "Corporate",
    icon: "🏢",
    description: "Professional coverage for conferences, product launches, award nights & brand events.",
    packages: [
      {
        id: "corporate-half",
        name: "Half Day",
        price: 15000,
        currency: "₹",
        duration: "4 Hours",
        description: "Focused coverage for half-day corporate events.",
        features: [
          "4 Hours Coverage",
          "1 Photographer",
          "200+ Edited Photos",
          "Event & Speaker Shots",
          "Online Gallery",
          "Commercial Usage License",
        ],
        cta: "Book Half Day",
      },
      {
        id: "corporate-full",
        name: "Full Day",
        price: 28000,
        currency: "₹",
        duration: "8 Hours",
        description: "Complete event documentation — stills and video.",
        popular: true,
        features: [
          "8 Hours Coverage",
          "2 Photographers",
          "400+ Edited Photos",
          "Event Highlight Reel — 3 min",
          "Stage, Networking & Detail Shots",
          "Same-Day Select Edits",
          "Commercial Usage License",
        ],
        cta: "Book Full Day",
      },
      {
        id: "corporate-premium",
        name: "Premium",
        price: 55000,
        currency: "₹",
        duration: "Multi-Day",
        description: "Premium multi-day coverage for large conferences.",
        features: [
          "Multi-Day Coverage",
          "3 Photographers + Videographer",
          "800+ Edited Photos",
          "Cinematic Brand Film — 5 min",
          "Drone Aerial (if permitted)",
          "Live Social Media Delivery",
          "Full Commercial License",
          "Priority Turnaround",
        ],
        cta: "Book Premium",
      },
    ],
  },

  // ── BIRTHDAY ───────────────────────────────────────────────────────────────
  {
    serviceId: "birthday",
    serviceLabel: "Birthday",
    icon: "🎂",
    description: "Milestone birthdays captured with joy — kids, adults, and grand celebrations.",
    packages: [
      {
        id: "birthday-celebration",
        name: "Celebration",
        price: 8000,
        currency: "₹",
        duration: "2 Hours",
        description: "Perfect for kids' birthdays and small gatherings.",
        features: [
          "2 Hours Coverage",
          "1 Photographer",
          "100+ Edited Photos",
          "Cake Smash / Candid Moments",
          "Online Gallery",
        ],
        cta: "Book Celebration",
      },
      {
        id: "birthday-grand",
        name: "Grand Bash",
        price: 18000,
        currency: "₹",
        duration: "4 Hours",
        description: "Extended coverage with highlight video.",
        popular: true,
        features: [
          "4 Hours Coverage",
          "2 Photographers",
          "250+ Edited Photos",
          "Highlight Reel — 2 min",
          "Group & Family Shots",
          "Venue & Décor Coverage",
          "Quick 48-Hour Delivery",
        ],
        cta: "Book Grand Bash",
      },
      {
        id: "birthday-royal",
        name: "Royal Affair",
        price: 35000,
        currency: "₹",
        duration: "Full Event",
        description: "Luxury birthday coverage — drone, film, and album.",
        features: [
          "Full Event Coverage",
          "2 Photographers + Videographer",
          "500+ Edited Photos",
          "Cinematic Film — 5 min",
          "Drone Aerial Shots",
          "Premium Photo Album (24 pages)",
          "Same-Day Teaser",
          "Priority Delivery",
        ],
        cta: "Book Royal Affair",
      },
    ],
  },
];
